### PR TITLE
DR8 Updates to LRGs for Main Survey and SV

### PR DESCRIPTION
**Pull request by geordie666**
This PR updates the LRG selections in the wake of DR8. It includes:
- A new LRG selection for SV, with fewer bits.
- A new ``LOWZ_FILLER`` class for SV.
- A new (and simplified) LRG selection for the Main Survey.
- Deprecation of the 1PASS/2PASS LRG convention, all LRGs now just have one observation.

I also deprecated some very old functions in the `desitarget.targets` module related to outdated conventions for `TARGETID`s and setting numbers of observations.

### CODE REVIEW

**Comment by geordie666** [comment]
@rongpu: It would be great if you could run this branch for a small area and check that the outputs agree with your expectations for the Main Survey and SV LRG selections.

@moustakas: I tried to maintain backwards-compatibility with the mocks, but, as always, I may have broken something while reformatting the LRG modules. If you could quickly check that everything still runs in this branch for a sample mock LRG or two, that'd be much appreciated.

**Comment by forero** [comment]
@geordie666 just to let you know that I will be opening a new PR that updates `make_mtl` and `calc_priorities` to fix some minor bugs that appear when you have targets with dual identities (i.e. both `ELG` and `QSO`). I will wait for you to merge this first. I will also need updated DR8 files before testing submitting my PR. Do you have them already somewhere?

**Comment by geordie666** [comment]
@forero: The latest catalogs are here:
```
/project/projectdirs/desi/target/catalogs/dr8/0.32.0/targets/main/resolve/dark
/project/projectdirs/desi/target/catalogs/dr8/0.32.0/targets/main/resolve/bright
```
Although I will probably make new versions once this PR is merged and once I've tagged a new version of the code.

Before you start, you may also want to check against #531 (which I will merge now), which forces MTL to have an observing condition (e.g. `"BRIGHT"`, `"GRAY|DARK"`) to resolve issues like #400.

Note, also, that with the review next week, I don't know how quickly we'll get around to merging this PR.

**Comment by rongpu** [comment]
@geordie666 I have run this branch of the desitarget code for a 100 sq deg area in both North and South, and as expected the resulting catalog is the same as the catalog produced by my own version of the code (I've checked both the baseline and SV samples, including the filler sample). So please go ahead and merge this PR.

**Comment by geordie666** [comment]
@moustakas: If you don't think this breaks the mocks, let me know and I'll merge this PR (I'll probably merge it early on Monday in any case)

**Comment by geordie666** [comment]
Actually, I'll need some extra time on Monday to complete this PR...@rongpu and I just remembered that we need one extra cut (and associated bit definitions) to delineate `4PASS` and `8PASS` LRGs for SV.

**Comment by forero** [comment]
@geordie666 I am checking against #531. It loooks like it solves many of the problems I was having.

**Comment by geordie666** [comment]
That's excellent to know, thanks @forero. #531 was a substantial PR, so if you find any issues with it, definitely let me know or push your own updates to further improve the code.

**Comment by forero** [comment]
@geordie666 @sbailey Indeed, #531 solves the dark/bright mixing problems I was having. I don't think I will be pushing the changes I had in mind.

**Comment by geordie666** [comment]
@rongpu: I've added the cuts (and bits) for ``_4PASS_`` and ``_8PASS_`` LRGs in SV. Please have one last look to check that everything behaves as you expect, now (particularly given the 4PASS/8PASS split). Then I'll merge this.

**Comment by rongpu** [comment]
I have checked the code changes in these commits, and everything looks good. Thanks!

**Pull request merged**
