### PR TITLE
various fixes to select_mock_targets

### PR DESCRIPTION
**Pull request by moustakas**
* Building on #558, `select_mock_targets` now uses `desitarget.io.find_target_files` to build the output file names for the *bright* and *dark* target and truth catalogs (no longer using `desitarget.mock.io.findfile`, which we should nevertheless keep).

* Adds a notebook, [mock-targets-to-mocks.ipynb](https://github.com/desihub/desitarget/blob/1446b834de3c3bc6193cfedd0ed0a7b21a262fb9/doc/nb/mock-targets-to-mocks.ipynb), which demonstrates how to use the `MOCKID` column to retrieve additional information about each mock target in the parent mock catalog (addressing #299 and #540).  I don't think the difficulties reported in the issues cited were due to a bug, but simply confusion with how the various mock catalogs are handled (owing to the various data models). 

* Fixes a bug (introduced in #543) in which object-specific metadata tables in the bright and dark categories were not trimmed from the output files as one would have expected.

@sbailey a question for you: I've changed here the output sky catalog to have the prefix `skies`, in order to match the file written out with "real" data (vs `sky`). Let me know if you would prefer I change this back.

Note that this PR will require a corresponding PR in `desisim` and an appropriate update to the `minitest` notebook.

### CODE REVIEW

**Comment by sbailey** [comment]
@moustakas ok if this breaks current integration if that is because it makes the mock data look more like real data (e.g. "sky" vs. "skies").  It would be especially helpful if you could also shepherd through the necessary updates to desisim and minitest.

Unit tests at NERSC with master of everything are currently failing at NERSC:
```
======================================================================
ERROR: test_targets_truth (desitarget.test.test_mock_build.TestMockBuild)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/test/test_mock_build.py", line 43, in test_targets_truth
    targets_truth(params, healpixels=[99737,], nside=256, output_dir=self.outdir, no_spectra=True)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/mock/build.py", line 983, in targets_truth
    qso_selection='colorcuts', mockdata=mockdata)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/io.py", line 528, in write_targets
    fitsio.write(truthfile+'.tmp', truthdata.as_array(), extname='TRUTH', header=hdr, clobber=True)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 245, in write
    with FITS(filename, 'rw', clobber=clobber, **keys) as fits:
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 353, in __init__
    self._FITS =  _fitsio_wrap.FITS(filename, self.intmode, create)
OSError: FITSIO status = 105: couldn't create the named file
failed to create new file (already exists?):
/tmp/tmp0w7tu5xw/997/99737/truth-256-99737.fits/targets/main/resolve/bright/trut
h-dr9-hp-99737.fits.tmp
```

Does this PR fix that?  If not could you try to add the fix for this here too?  Thanks.

**Comment by moustakas** [comment]
> Does this PR fix that? If not could you try to add the fix for this here too? Thanks.
Yes, this PR fixes this issue, which was introduced in #558.

**Comment by sbailey** [comment]
This PR looks fine and works with the minitest notebook.  However, I find that it is still writing "sky-64-5283.fits" instead of "skies-64-5283.fits".  I'm fine with either option, but the original PR post seemed to indicate the opposite:

> @sbailey a question for you: I've changed here the output sky catalog to have the prefix skies, in order to match the file written out with "real" data (vs sky). Let me know if you would prefer I change this back.

@moustakas can you confirm the intended behavior here?

Specifically I ran
```
cd /global/cscratch1/sd/sjbailey/minitest-19.11/targets
select_mock_targets -c select-mock-targets.yaml -O . -s 1013994432 --nside 64 --nproc 4 --healpixels 5283
...
INFO:build.py:982:targets_truth: Writing 1024 SKY targets to /global/cscratch1/sd/sjbailey/minitest-19.11/targets/52/5283/sky-64-5283.fits
INFO:select_mock_targets:103:<module>: All done at Thu Nov  7 15:00:33 2019
```

**Comment by moustakas** [comment]
Yes, sorry, I over-ruled myself and went with a `sky` prefix to not break more of the downstream code.  Unless you want `skies` let's just keep it as-is.

If everything else looks OK let's merge and I can implement whatever other downstream issues arise in https://github.com/desihub/desisim/pull/514.

In particular, note that the mock target files now *do* contain the `obscon` suffix, e.g., `targets-dark-128-104121.fits`.

**Comment by sbailey** [comment]
Yep, looks good, thanks.  Merging now.

**Pull request merged**
