### PR TITLE
Update to BGS selection for SV

### PR DESCRIPTION
**Pull request by geordie666**
This PR updates the SV selection for SV and introduces several more BGS SV bits including `BGS_FAINT_EXT`, `BGS_LOWQ` and `BGS_FIBMAG`.

### CODE REVIEW

**Comment by geordie666** [comment]
Awaiting review by @qmxp55. See also PR https://github.com/desihub/desitarget/pull/455.

**Comment by qmxp55** [comment]
Thanks @geordie666 I have ran this PR for SV and the output catalogue match with my own selectios for every single BGS bits.

Just to be clear, I used these to select the BGS bits (BGS_BRIGHT example):

from sv1.sv1_targetmask import bgs_mask
bgs_bright = (df['SV1_BGS_TARGET'] & bgs_mask['BGS_BRIGHT'])!=0

**Comment by geordie666** [comment]
Thanks @qmxp55: Can you update the selection recorded on the SV wiki page:

https://desi.lbl.gov/trac/wiki/TargetSelectionWG/SurveyValidation

So that I can include the versioning in the doc strings of the code? I'll merge once I've updated those doc strings.

**Comment by qmxp55** [comment]
Done! 
Thanks @geordie666

**Pull request merged**
