### PR TITLE
Updates to BGS targeting

### PR DESCRIPTION
**Pull request by geordie666**
This PR builds on:

https://github.com/qmxp55/desitarget/tree/bgs_target

to update the target selection for BGS. Includes:

* Updates to `BGS_FAINT` and `BGS_BRIGHT` target selections.
* New `BGS_WISE` selection and implementation.
* New data model columns `BRIGHTSTARINBLOB` and `FRACIN_`.
* Modification to I/O to retain backwards-compatibility between DR6 and DR7 data models.
* Updated unit test example files with appropriate columns.

### CODE REVIEW

**Comment by sbailey** [comment]
Regarding
> * New data model columns BRIGHTSTARINBLOB and FRACIN_.
> * Modification to I/O to retain backwards-compatibility between DR6 and DR7 data models.

Adding new columns to the output is ok.  If I understood correctly, this also required additional columns to the input which aren't in the DR6/DR7 sweeps, which seems much more disruptive.  Is "Modification to I/O to retain backwards-compatibility between DR6 and DR7 data models" meaning that you can proceed even with the sweeps that don't have those columns?  Is there any impact to mock making (e.g. requiring columns that mocks aren't yet providing?).

I'd prefer to wait until after the collaboration meeting to merge this, but if it is needed urgently for collaboration meeting evaluation, we could merge it.  Or just generate example TS output files using this branch while still not merging it yet.

**Comment by moustakas** [comment]
Sorry, I mis-spoke/mis-wrote about `FRACIN_[G,R,Z]` not being in the sweeps.  Behold---
  http://legacysurvey.org/dr7/files/#sweep-7-0-sweep-brickmin-brickmax-fits

**Comment by geordie666** [comment]
Yep, `FRACIN_` is in the sweeps. The thing that required a little special handling on I/O for backwards compatibility was `BRIGHTSTARINBLOB`. I set `BRIGHTSTARINBLOB` to false for all objects for DR6 input, but I needed to make sure that it was included as a data model column for algorithms that want to include it as a factor.

I don't think this code is needed urgently for the collaboration meeting, and I'd like @qmxp55 to take a look at it before we merge it, so feel free to hold off merging it until after the meeting.

**Comment by qmxp55** [comment]
@geordie666, @moustakas, @sbailey: Great to hear everything is in place. I don't think this is needed urgently for the collaboration meeting as well. I will carry the test and let you know of any issue that may came out. About the priorities, this is not settle yet, I just copied the BGS FAINT. For this matter I need to discuss it with BGS group, which I haven't yet.

Thank you.

**Comment by geordie666** [comment]
@qmxp55: Thanks for agreeing to review my work. 

Let's not let a future discussion of priorities delay your code getting into master. Updating the priorities would be an easy fix in the future.

**Comment by geordie666** [comment]
I added some additional work in this branch that relied on having `BRIGHTSTARINBLOB` in the data model: 

- The quasar code is now updated to use `BRIGHTSTARINBLOB`.
- I had to update `test_cuts` to cover `BRIGHTSTARINBLOB`. 
- While working on unit tests I performed a long overdue overhaul of `test_cuts` which speeds up tests without losing coverage.

I don't intend to work on this branch any further now, though, so we can merge as soon as @qmxp55 confirms that the new BGS cuts (and bits) look correct.

**Comment by qmxp55** [comment]
@geordie666 Thanks for pushing this. I've ran BGStargetADM branch for a small region ~200 s.deg and compared the results with my results and they match. Everything seems to work fine.

**Comment by geordie666** [comment]
Thanks @qmxp55, I'll merge this soon.

**Pull request merged**
