### PR TITLE
No override sv3

### PR DESCRIPTION
**Pull request by jalasker**
Stops adding the OVERRIDE keyword to the meta dictionary for the SV3(and 2 and 1) and CMX MTLs since the presence of that keyword causes problems downstream in the alternate MTL code.

I would prefer to wait on merging this pull request until I have confirmed that it doesn't create undesired effects in the final alternate MTL bitweight products, but I can confirm that it does have the desired effect in the initial and intermediate stages of the alternate MTL pipeline.

### CODE REVIEW

**Review by geordie666 — CHANGES_REQUESTED** [review]
I tried running this on the "real" `main` ledgers, and everything seems to still work. Good!

Other than removing the few stray lines of white-space to conform to PEP 8 (as noted in the detailed review) please also: 

- Update the [changes.rst](https://github.com/desihub/desitarget/blob/master/doc/changes.rst) file to include (and link to) this PR (PR 767).

It's also hard to review all of the introduced white-space, but according to the unit tests the full list of blank lines with added white-space is:
```
py/desitarget/io.py: 2913
py/desitarget/io.py: 2916
py/desitarget/io.py: 2919
py/desitarget/io.py: 2923
py/desitarget/io.py: 2926
py/desitarget/io.py: 2930
py/desitarget/io.py: 2933
py/desitarget/mtl.py: 1174
```

**Comment by jalasker** [comment]
The initial step of generating the MTLs is working fine with the new branch as is most of the updating process. 

However, I am now timing out at the last step of the update on this comment: 

INFO:mtl.py:1165:process_overrides: Processing override ledgers

There shouldn't be any overrides to process since this is SV3. I am not sure if the process is actually hanging or if it is a process that would complete given a longer time allotment. I can dig in more, but that will cost some core hours and time, so I was hoping someone in this thread might be able to tell what is going on.

**Comment by michaelJwilson** [comment]
Compared to Adam, I'm going to be of no help, but am invested enough to ask:  what is the script you call this?  Where is the output?  When I tried with this new branch I hit a new problem of not finding redshifts, but I assume that was a calling error.

**Comment by geordie666** [comment]
@jalasker: When I run the MTL loop on the regular data using the branch that is now in `master`, I receive your message about overrides, but there's no hanging and the task quickly runs to completion. Here's an example of the output for a test case:
```
[adamyers@cori07 mtl]$ run_mtl_loop DARK --mtldir /global/cscratch1/sd/adamyers/fakesurveyops2/mtl
INFO:mtl.py:2025:loop_ledger: running on SECONDARY ledger with obscon=DARK and survey=main
INFO:mtl.py:2070:loop_ledger: Update state for 33652 targets (the zcats also contain 669 skies with +ve TARGETIDs)
INFO:mtl.py:416:make_mtl: Ignoring 33145 z entries that aren't in the input target list (e.g. likely skies, secondaries-when-running-primary, primaries-when-running-secondary, etc.)
INFO:mtl.py:424:make_mtl: Ignoring a further 11 zcat entries with NODATA set
INFO:mtl.py:431:make_mtl: Ignoring a further 2 zcat entries with BAD_SPECQA or BAD_PETALQA set
WARNING:mtl.py:437:make_mtl: The size of the zcat has changed, so it won't be modified!
INFO:targets.py:866:calc_priority: 1163 scnd targets to be updated as secondary-only
INFO:targets.py:897:calc_priority: 0 more scnd targets allowed to update MWS primaries
INFO:targets.py:902:calc_priority: 1163 scnd targets to be updated in total
INFO:mtl.py:512:make_mtl: 1041 of 69187 targets have priority <=2, setting N_obs=0.
INFO:mtl.py:587:make_mtl: Done...t=0.2s
INFO:mtl.py:1165:process_overrides: Processing override ledgers
INFO:mtl.py:1165:process_overrides: Processing override ledgers
INFO:mtl.py:1165:process_overrides: Processing override ledgers
INFO:mtl.py:1165:process_overrides: Processing override ledgers
INFO:mtl.py:1165:process_overrides: Processing override ledgers
INFO:mtl.py:1165:process_overrides: Processing override ledgers
INFO:mtl.py:1165:process_overrides: Processing override ledgers
INFO:run_mtl_loop:52:<module>: MTL ledger directory: /global/cscratch1/sd/adamyers/fakesurveyops2/mtl/main/secondary/dark
INFO:run_mtl_loop:53:<module>: MTL tile file: /global/cscratch1/sd/adamyers/fakesurveyops2/mtl/scnd-mtl-done-tiles.ecsv
INFO:run_mtl_loop:54:<module>: Redshift tile file: /global/cscratch1/sd/adamyers/fakesurveyops2/ops/tiles-specstatus.ecsv
INFO:run_mtl_loop:55:<module>: Processed 8 new tiles, which are: [( 3140, '2021-11-05T01:16:08+00:00', '1.3.0.dev5218', 'DARK', '20211009')
 ( 4817, '2021-11-05T01:16:08+00:00', '1.3.0.dev5218', 'DARK', '20211003')
 ( 6367, '2021-11-05T01:16:08+00:00', '1.3.0.dev5218', 'DARK', '20211007')
 ( 6538, '2021-11-05T01:16:08+00:00', '1.3.0.dev5218', 'DARK', '20211009')
 ( 8077, '2021-11-05T01:16:08+00:00', '1.3.0.dev5218', 'DARK', '20211009')
 ( 9355, '2021-11-05T01:16:08+00:00', '1.3.0.dev5218', 'DARK', '20211008')
 ( 9630, '2021-11-05T01:16:08+00:00', '1.3.0.dev5218', 'DARK', '20211008')
 (10542, '2021-11-05T01:16:08+00:00', '1.3.0.dev5218', 'DARK', '20211008')]
INFO:mtl.py:2028:loop_ledger: running on PRIMARY ledger with obscon=DARK and survey=main
INFO:mtl.py:2070:loop_ledger: Update state for 33652 targets (the zcats also contain 669 skies with +ve TARGETIDs)
INFO:mtl.py:416:make_mtl: Ignoring 1845 z entries that aren't in the input target list (e.g. likely skies, secondaries-when-running-primary, primaries-when-running-secondary, etc.)
INFO:mtl.py:424:make_mtl: Ignoring a further 266 zcat entries with NODATA set
INFO:mtl.py:431:make_mtl: Ignoring a further 69 zcat entries with BAD_SPECQA or BAD_PETALQA set
WARNING:mtl.py:437:make_mtl: The size of the zcat has changed, so it won't be modified!
INFO:targets.py:866:calc_priority: 0 scnd targets to be updated as secondary-only
INFO:targets.py:897:calc_priority: 0 more scnd targets allowed to update MWS primaries
INFO:targets.py:902:calc_priority: 0 scnd targets to be updated in total
INFO:mtl.py:512:make_mtl: 28993 of 600146 targets have priority <=2, setting N_obs=0.
INFO:mtl.py:587:make_mtl: Done...t=3.2s
INFO:run_mtl_loop:52:<module>: MTL ledger directory: /global/cscratch1/sd/adamyers/fakesurveyops2/mtl/main/dark
INFO:run_mtl_loop:53:<module>: MTL tile file: /global/cscratch1/sd/adamyers/fakesurveyops2/mtl/mtl-done-tiles.ecsv
INFO:run_mtl_loop:54:<module>: Redshift tile file: /global/cscratch1/sd/adamyers/fakesurveyops2/ops/tiles-specstatus.ecsv
INFO:run_mtl_loop:55:<module>: Processed 8 new tiles, which are: [( 3140, '2021-11-05T01:16:22+00:00', '1.3.0.dev5218', 'DARK', '20211009')
 ( 4817, '2021-11-05T01:16:22+00:00', '1.3.0.dev5218', 'DARK', '20211003')
 ( 6367, '2021-11-05T01:16:22+00:00', '1.3.0.dev5218', 'DARK', '20211007')
 ( 6538, '2021-11-05T01:16:22+00:00', '1.3.0.dev5218', 'DARK', '20211009')
 ( 8077, '2021-11-05T01:16:22+00:00', '1.3.0.dev5218', 'DARK', '20211009')
 ( 9355, '2021-11-05T01:16:22+00:00', '1.3.0.dev5218', 'DARK', '20211008')
 ( 9630, '2021-11-05T01:16:22+00:00', '1.3.0.dev5218', 'DARK', '20211008')
 (10542, '2021-11-05T01:16:22+00:00', '1.3.0.dev5218', 'DARK', '20211008')]
```

The `INFO:mtl.py:1165:process_overrides: Processing override ledgers` steps are nearly instantaneous. So, basically, I can't recreate your bug. Can you come up with a simple example I can try to run to debug?

If you want to try my example for (a fake copy of) the "real" data:

- Copy the `/global/cscratch1/sd/adamyers/fakesurveyops2` directory to your scratch space. Let's call that directory `/global/cscratch1/sd/jlasker/fakesurveyops2`
- Go into `/global/cscratch1/sd/jlasker/fakesurveyops2/mtl/mtl-done-tiles.ecsv` and remove the last few dark tiles (so they will be re-run by MTL).
- Make sure you have the `$ZCAT_DIR` environment variable set to `/global/cfs/cdirs/desi/spectro/redux/daily`.
- Issue `run_mtl_loop DARK --mtldir /global/cscratch1/sd/jlasker/fakesurveyops2/mtl`. Make _absolutely_ sure to pass `--mtldir` so as not to corrupt your existing `$MTL_DIR` directory!

**Comment by jalasker** [comment]
I ran my own job again and it wasn't hanging anymore. I think the original hangup was a result of some parallel job taking too long or an I/O collision causing an unexpected delay. (@michaelJwilson I will eventually have documentation up on the wiki with the code that I'm running, but for now I'm not even certain the current version of the altmtl code is in the LSS github. The script is /global/cfs/cdirs/desi/survey/catalogs/SV3/LSS/altmtl/debug_jl/dateLoopAltMTL.sh which calls runAltMTLParallel.py in the same directory.). 

However, once the code was running again, it showed some additional errors regarding being unable to find the keyword "NUMOVERRIDE" in one of the SV3 MTLs: 

"""
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/global/cfs/cdirs/desi/survey/catalogs/SV3/LSS/altmtl/debug_jl/runAltMTLParallel.py", line 65, in procFunc
    amt.loop_alt_ledger(obscon, survey = survey, mtldir = mtldir, zcatdir = zcatdir, altmtlbasedir = altmtlbasedir, ndirs = ndirs, numobs_from_ledger = numobs_from_ledger,secondary = secondary, getosubp = getosubp, quickRestart = quickRestart, multiproc = multiproc, nproc = nproc, singleDate = singleDate, redoFA = redoFA)
  File "/global/homes/j/jlasker/.local/desicode/LSS/py/LSS/SV3/altmtltools.py", line 607, in loop_alt_ledger
    update_ledger(althpdirname, altZCat, obscon=obscon.upper(),
  File "/global/homes/j/jlasker/.local/lib/python3.8/site-packages/desitarget/mtl.py", line 1472, in update_ledger
    overmtl = process_overrides(overfn)
  File "/global/homes/j/jlasker/.local/lib/python3.8/site-packages/desitarget/mtl.py", line 1175, in process_overrides
    mtl["NUMOVERRIDE"] -= 1
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/table.py", line 1602, in __getitem__
    return self.columns[item]
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/table.py", line 239, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'NUMOVERRIDE'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/cfs/cdirs/desi/survey/catalogs/SV3/LSS/altmtl/debug_jl/runAltMTLParallel.py", line 97, in <module>
    result = p.map(procFunc,inds)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 'NUMOVERRIDE'



Adding additional print/log statements into the process_override function and adjacent functions, I was able to find that it was looking for a non-override MTL (e.g. /global/cfs/cdirs/desi/survey/catalogs/SV3/LSS/altmtl/debug_jl/alt_mtls_testAdamOverrideFix_64dirs//Univ056/sv3/dark/sv3mtl-dark-hp-2594.ecsv) in the process_override function.

I added a check to only try to run process_override within update_ledger if the MTL file contained "override" as part of the file name and that seemed to get it to work. 

I think the optimal way to fix this would probably be to modify find_mtl_file_format_from_header with the override option so that it only finds override MTLs, but I am not sure how to do that.

**Comment by jalasker** [comment]
@geordie666 I re-pulled the desitarget code after the recent updates and I'm still getting errors. I also cannot get your example to work. It fails asking for the field "ARCHIVE_DATE"

jlasker@cori05:/global/cscratch1/sd/jlasker/fakesurveyops2/mtl> run_mtl_loop DARK --mtldir /global/cscratch1/sd/jlasker/fakesurveyops2/mtl/
WARNING: leap-second auto-update failed due to the following exception: RuntimeError('Cache is locked after 5.03 s. This may indicate an astropy bug or that kill -9 was used. If you want to unlock the cache remove the directory /global/homes/j/jlasker/.astropy/cache/download/py3/lock.') [astropy.time.core]
INFO:mtl.py:2303:loop_ledger: running on SECONDARY ledger with obscon=DARK and survey=main
Traceback (most recent call last):
  File "/global/homes/j/jlasker/.local/bin/run_mtl_loop", line 52, in <module>
    hpdirname, mtltilefn, tilefn, tiles = loop_ledger(
  File "/global/homes/j/jlasker/.local/lib/python3.8/site-packages/desitarget/mtl.py", line 2313, in loop_ledger
    tiles = tiles_to_be_processed(zcatdir, mtltilefn, obscon, survey,
  File "/global/homes/j/jlasker/.local/lib/python3.8/site-packages/desitarget/mtl.py", line 2035, in tiles_to_be_processed
    newtiles["ARCHIVEDATE"] = tiles["ARCHIVEDATE"]
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/table.py", line 1602, in __getitem__
    return self.columns[item]
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/table.py", line 239, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'ARCHIVEDATE'

**Comment by geordie666** [comment]
We updated the `mtl-done-tiles.ecsv` and `scnd-mtl-done-tiles.ecsv` files to have a new column `ARCHIVEDATE`. This is to facilitate reprocessing of tiles, as the spectroscopic pipeline is now storing the redshift files in the directory `$ZCAT_DIR/tiles/archive/ARCHIVEDATE` rather than in the `cumulative` directory.

The first step in fixing the loop for the alternate MTLs would be to copy across the "official" MTL done files from:
```
/global/cfs/cdirs/desi/survey/ops/surveyops/trunk/mtl/mtl-done-tiles.ecsv
/global/cfs/cdirs/desi/survey/ops/surveyops/trunk/mtl/scnd-mtl-done-tiles.ecsv
```
(which contain the `ARCHIVEDATE` column).

Note that I'm currently working on a PR to complicate this yet further by allowing reprocessed tiles to be passed through MTL. So, you might not want to delve into this too deeply until all of the new MTL infrastructure is in place (until then you could use an earlier tag of `desitarget`, perhaps?).

**Comment by geordie666** [comment]
@jalasker: I'm just getting back to this after the various extra MTL updates.

Do you want to test the current branch and see if we need further updates to facilitate working with the alternate MTLs?

Also, should we close this PR and pick up any needed work in a new branch?

**Comment by jalasker** [comment]
Sorry, I was traveling home today. I will test the current branch tomorrow and let you know if we still need a fix for the override code with SV3.

**Comment by jalasker** [comment]
Running the tests you described on the MTLs you described/linked above works for me after grabbing the updated files. 

It is also not failing on the alternate MTLs but is not updating any targets. 

I believe that I have some updates to make to the alt MTL loop, possibly passing some additional options that weren't present in the original loop_ledger function.

**Comment by geordie666** [comment]
@jalasker: Great, glad this works in the short-term. Is it OK to close this PR and work on any other updates in a new branch spawned from the current master branch?

**Comment by jalasker** [comment]
So I think it is fine to work on the updates in a new branch with the latest code version.  

However, I am still getting the errors about looking for "NUMOVERRIDE" even with the latest code. (The reason that it didn't fail last night is that I forgot to re-remove the tiles that I originally removed from the mtl-tiles-done file that I copied from your fakesurveyops2 directory. Once I removed those tiles and it actually tried to update the MTLs it failed with the same error.)

**Comment by geordie666** [comment]
OK, let me close this and open an issue instead. I can then work on fixing the `NUMOVERRIDE` problem in a separate branch.

**Pull request closed without merging**
