### PR TITLE
Update sample GMMs to DR5

### PR DESCRIPTION
**Pull request by belaa**
This PR addresses Issue #250, and includes new sets of gaussian mixture models based on colors and one magnitude for each target type. The new code is in `desitarget/mock/sample_colors.py` and the gmms can be found in `desitarget/mock/data/dr5/colors/`. A reference notebook showing how the gmms were created is also included in `doc/nb/dr5_mag_color_distributions.ipynb`.

### CODE REVIEW

**Comment by sbailey** [comment]
Original Travis tests failed due to a transient segfault which seems to have been fixed on the travis-ci.org side (it wasn't unique to this repo).  Now tests are failing due to 
```
======================================================================
ERROR: test_sample_mag_shape (desitarget.test.test_sample.TestSample)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/desihub/desitarget/py/desitarget/test/test_sample.py", line 13, in setUp
    self.lrg = GaussianMixtureModel.load(self.modelpath + '/lrg_gmm.fits')
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/desiutil/sklearn.py", line 75, in load
    hdus = fits.open(filename, memmap=False)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/astropy/io/fits/hdu/hdulist.py", line 160, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/astropy/io/fits/hdu/hdulist.py", line 413, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/astropy/io/fits/hdu/hdulist.py", line 998, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/astropy/io/fits/util.py", line 409, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/desihub/desitarget/py/desitarget/mock/data/lrg_gmm.fits'
```
Did you forget to add this file to the repo?

**Comment by sbailey** [comment]
Some tests are still failing due to looking for lrg_gmm.fits in the wrong location.  Please keep iterating with `python py/desitarget/test/test_sample.py` (i.e. you don't need to wait for Travis iterations to debug this).

**Comment by sbailey** [comment]
@moustakas requested the updated GMMs in #250; do you have time to check if this matches what you need?

**Comment by moustakas** [comment]
I don't have time to test this in the simulation pipeline itself right now, but it's a significant improvement over what we've been using so I'm going to merge.  Plus @belaa and I have been corresponding off-list -- thank you @belaa!

**Pull request merged**
