### PR TITLE
Add STD_WD target class to main survey cuts

### PR DESCRIPTION
**Pull request by geordie666**
This PR adds the `STD_WD` class to `desitarget.cuts` and sets that bit in output files. The `STD_WD` class is currently identical to the `MWS_WD` class.

Also adds a `_prepare_optical_wise` function to clean up some of the initial setting of columns of data, and utilizes that function and the `_prepare_gaia` function in `cmx_cuts`.

### CODE REVIEW

**Comment by moustakas** [comment]
@weaverba137  We need your expertise with some failing Travis tests, which have somehow infected `desitarget/master`.

In @geordie666's original PR the error was
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda==4.3.34
  - conda[version='>=4.5.11']
Use "conda info <package>" to see the dependencies for each package.
```
See here:  https://travis-ci.org/desihub/desitarget/jobs/424442104#L723-L726

Now (after I fixed a simple conflict in the change log) the error is 
```
ImportError: No module named 'fitsio'
```
See here:  https://travis-ci.org/desihub/desitarget/jobs/424725185#L1410

Any thoughts or suggestions?

**Comment by weaverba137** [comment]
This is a known problem with the ci-helpers package that was noticed yesterday.  Let's see if a fix comes out today.

**Comment by geordie666** [comment]
@moustakas: Thanks for looking into the unit test failures. This branch is still failing with the `import fitsio` error (despite `fitsio` being a dependency in `.travis.yml`). I say we merge this without changes so we can keep developing, and dig into Travis issues more once the fix @weaverba137 mentioned emerges. Any objections?

**Comment by moustakas** [comment]
Merge away!

**Comment by weaverba137** [comment]
In fact, this problem may be upstream to ci-helpers, in conda itself, see conda/conda#7734.

**Pull request merged**
