### PR TITLE
restore the no-spectra option to select_mock_targets

### PR DESCRIPTION
**Pull request by moustakas**
This PR addresses #286 by restoring the no-spectra option to `select_mock_targets`

An example configuration file is in `/global/cscratch1/sd/ioannis/nospectra` and the code was tested (on my laptop, not NERSC, with 4 cores) using
```
time select_mock_targets -c nospectra.yaml --no-spectra --verbose --seed 5 --healpixels 26028 26029 --nside 64 --overwrite --nproc 4
join_mock_targets --mockdir . --force
run_target_qa ./targets.fits html/ --mocks
```
The output catalogs have >11,000 objects (of all types) and were generated in roughly 2 minutes. The resulting QA plots are [here](http://portal.nersc.gov/project/cosmo/temp/ioannis/nospectra-html/).

@julienguy if you could test the code on a few hundred square degrees before deploying to the full DESI footprint then I can track down any outstanding issues.

### CODE REVIEW

**Comment by moustakas** [comment]
Adding a bit more info and requesting a review by @forero:

Observed-frame colors, reference magnitudes, and--in the case of ELGs--[OII] fluxes are generated using Gaussian mixture models trained on the `18.3 release` reference catalogs (which produce full spectra).  These mixture models are trained just on the extra-galactic targets--ELGs, LRGs, QSOs, LYA QSOs, and BGS.  Here's the [notebook](https://github.com/desihub/desitarget/blob/435afe8ff6cc1c26fbc60e524ee42fd81a5df42b/doc/nb/gmm-quicksurvey.ipynb) for review.

For stars the colors are synthesized from the basis templates themselves.

The updated code (`mock.build.targets_truth` and `mock.mockmaker`) also includes additional speed improvements, e.g., by reading once and caching the basis templates and mock catalog coordinates.  This should help scaling at NERSC by keeping many nodes accessing the same files concurrently.  Thanks to @sbailey and @julienguy for various code suggestions along these lines.

Finally, for comparison, I ran the same two healpixels *with* spectra (just by dropping the `--no-spectra` option) and it took 9m21s.  So the `quicksurvey` version of this code is approximately five times faster.

After this PR is merged I'll work on #285 (tune contaminant densities).

**Comment by julienguy** [comment]
Except for those few errors, the code is working smoothly on a full DESI mock (several 10 million spectra). I am trying to fix them.

**Comment by moustakas** [comment]
@julienguy Unless you've already started I can try to track down these issues.  For both problems if you point me to the logfile(s) I'll try to reproduce and fix the issues.  But for problem (2) it sounds like the sky mock produced by @sbailey needs to be sampled with a higher density.

**Comment by forero** [comment]
@moustakas Thanks for this update! I am testing now and got some errors from a missing galaxia pixel file (I believe this has been reported before)
```
OSError: File not found: '/project/projectdirs/desi/mocks/mws/galaxia/alpha/0.0.5_superfaint/healpix/8/0/1/mock_superfaint_allsky_galaxia_desi_b10_cap_south-8-1.fits'
```

**Comment by forero** [comment]
@moustakas I am running full DESI mocks with large pixels (`--nside 4`) and it seems that the code is not handling properly empty pixels. It looks very much the same as the error pointed out by @julienguy.

```
WARNING:mockmaker.py:1386:readmock: No BGSs in healpixels 7!
1423042237
INFO:build.py:347:density_fluctuations: Dividing each nside=4 healpixel (214.86 deg2) into 1024 nside=128 healpixel(s) (0.21 deg2).
Traceback (most recent call last):
  File "/global/homes/f/forero/desitarget/bin/select_mock_targets", line 108, in <module>
    no_spectra=args.no_spectra)
  File "/global/homes/f/forero/desitarget/py/desitarget/mock/build.py", line 562, in targets_truth
    nproc=nproc, sky=sky, no_spectra=no_spectra)
  File "/global/homes/f/forero/desitarget/py/desitarget/mock/build.py", line 424, in get_spectra
    data, log, nside=nside, nside_chunk=nside_chunk, seed=seed)
  File "/global/homes/f/forero/desitarget/py/desitarget/mock/build.py", line 351, in density_fluctuations
    healpix_chunk = radec2pix(nside_chunk, data['RA'], data['DEC'])
KeyError: 'RA'
```

**Comment by moustakas** [comment]
Thanks @forero, yes, I'm working on this fix now.  But note that `nside=4` will likely result in memory issues at NERSC (although we should test it!);  I've been suggesting `nside=32` or perhaps even `nside=16`.

Here's a bit more info about how the code is structured:  `mock.targets_truth` loops over input healpixels in its outer loop and then target classes in its inner loop (at the end of which the catalogs are all written out).  In a given healpixel and target type, however, the targets are subdivided (chunked) into smaller ealpixels (the default is `nside=128`) and then the code is parallelized over these smaller chunks.  

If the input `nside` is too small then it's likely the code will either run out of memory (even without spectra it needs to hold the tables of all the various targets classes in memory) or finish within the 30-minute debugging queue.

We should really figure out what value of `nside` (and the `npix` optional argument in `mpi_select_mock_targets`) will optimally allow the code to complete the full footprint.

**Comment by moustakas** [comment]
@forero I think I fixed the crash you identified --

```
(desi) ioannis@atlas:~/work/desi/datachallenge/nospectra% time select_mock_targets -c failures.yaml --verbose --seed 77777 --healpixels 7 --nside 4 --overwrite --nproc 4 --no-spectra
INFO:select_mock_targets:44:<module>: Starting select_mock_targets at Thu Apr 26 09:30:54 2018
INFO:select_mock_targets:71:<module>: Processing 1 pixel(s).
INFO:select_mock_targets:98:<module>: Reading configuration file failures.yaml
INFO:select_mock_targets:102:<module>: Calling targets_truth at Thu Apr 26 09:30:54 2018
WARNING:build.py:87:initialize_targets_truth: Output directory ./ is not empty.
INFO:build.py:91:initialize_targets_truth: Writing to output directory ./
INFO:build.py:95:initialize_targets_truth: Processing 1 healpixel(s) (nside = 4, 214.859 deg2/pixel) spanning 214.859 deg2.
INFO:io.py:1010:read_basis_templates: Reading /Users/ioannis/work/desi/spectro/templates/basis_templates/v2.5/bgs_templates_v2.1.fits
77777
INFO:build.py:547:targets_truth: Working on healpixel 7
INFO:build.py:559:targets_truth: Working on target class: BGS
INFO:build.py:149:read_mock: Target: BGS, format: durham_mxxl_hdf5, mockfile: /Users/ioannis/work/desi/mocks/bgs/MXXL/desi_footprint/v0.0.4/BGS.hdf5
INFO:mockmaker.py:1358:_read_mockfile: Assigning healpix pixels with nside = 4
WARNING:mockmaker.py:1386:readmock: No BGSs in healpixels 7!
INFO:select_mock_targets:106:<module>: All done at Thu Apr 26 09:31:07 2018

real    0m14.303s
user    0m11.716s
sys     0m2.435s
```

**Comment by forero** [comment]
@moustakas yes, you did! I am running now the full DESI mock. I will let you know later about the results.

**Comment by julienguy** [comment]
Feel free to merge this PR which is great progress!
I was able to run a full DESI set of mocks in 2h30min with 10 cori nodes without a single error.
That's 49M targets (the mock is significantly oversampled by a factor 2 to 3). I did: 
```
srun -N 10 -n 40 -c 16 mpi_select_mock_targets --nside 32 --nproc 16 --no-spectra --seed X --output_dir XXX --config select-mock-targets.yaml
```

**Comment by moustakas** [comment]
Thanks @julienguy can you post the location of the output catalogs here so I can generate the QA? The oversampling is likely due to #285.  I'll work on that next.

**Comment by forero** [comment]
@julienguy Using that commant I got the error
```
Traceback (most recent call last):
  File "/global/homes/f/forero/desitarget/bin/mpi_select_mock_targets", line 89, in <module>
    for i, pixnum in enumerate(pixels):
TypeError: iteration over a 0-d array
```
because nothing was passed as tiles or healpixels.

**Comment by julienguy** [comment]
Sorry about this, I ran with an additional option ```--healpixels $pixels```
```
srun -N $nodes -n $nproc -c $nthread mpi_select_mock_targets --nside $nside --output_dir XXX  --config XXX.yaml --healpixels $pixels --seed $seed --nproc $nthread --no-spectra
```

with $pixels from
```
pixmap    = pyfits.open(os.path.join(os.environ['DESIMODEL'],'data','footprint','desi-healpix-weights.fits'))[0].data
pixweight = load_pixweight(args.nside, pixmap=pixmap)
pixels    = np.where(pixweight>0)[0]
```

I ran a full mock:
 - in 2h30min with a job of 10 cori haswell nodes with -N 10 -n 40 -c 16
 - in less than 30min with a job of 60 edison nodes with -N 60 -n 240 -c 12

I am currently running ```join_mock_targets``` and will post here the path to the mocks for you to run the QA.

**Comment by julienguy** [comment]
- The low-z QSO sample ends at z=2.15  and the high-z QSO/Lya sample starts at z=2. So, there is some overlap. I should have truncated one of the two. I am not sure how to do it in the yaml file.

- However, overlap or not, I don't think we can avoid a discontinuity in the density vs z. 
- The QSO clustering analysis should have a limited z-range to avoid pollution with the high-z sample.
- We need the high-z sample for its impact on fiber assignment of lower z targets.

**Comment by moustakas** [comment]
It looks like you might need to `svn up` your desimodel, @forero.  The new goal target density of LRGs is 480/deg, and it looks like we're hitting it spot-on.

And the QSO and ELG target densities are low because I haven't included contaminants in the proper proportion yet.  Similarly, if you made the QA for BGS you would see that the number of contaminating stars is far too high.

So overall things look good!

**Comment by moustakas** [comment]
```The low-z QSO sample ends at z=2.15 and the high-z QSO/Lya sample starts at z=2. So, there is some overlap. I should have truncated one of the two. I am not sure how to do it in the yaml file.```
There's an open issue on this, https://github.com/desihub/desitarget/issues/308.  We simply need to agree when (at what redshift) the QSO mocks should stop and the Lya mocks should begin.

Or we *could* put a `zmax` parameter in the config file (e.g., for the QSOs) but then how do you enforce continuity with whatever Lya mock you put into the same config file?  That's a fragile solution.

**Pull request merged**
