### PR TITLE
Fix overwrite in select_mock_targets

### PR DESCRIPTION
**Pull request by alxogm**
This PR fixes https://github.com/desihub/desitarget/issues/582. By replacing the use of 

` desitarget.mock.io ` for  `desitarget.io.find_target_files` to locate the appropriate dark and bright truthfiles... it will always look for both files. I tested adding an option to check for only dark or bright, but I'm not sure how useful this will actually be so I'm just making this simplest PR, and later if I find more useful to have such option I'll open a new issue. 

I've tested this PR in both cases mpi_ and non-mpi

### CODE REVIEW

**Comment by geordie666** [comment]
As usual, please document this PR in the [changes file](https://github.com/desihub/desitarget/blob/master/doc/changes.rst) before merging.

**Comment by moustakas** [comment]
@alxogm I tested this with
```time select_mock_targets -c ./select-mock-targets.yaml --nproc 12 --verbose --seed 1 --healpixels 104118 --nside 128```
using a configuration file (for speed) containing just LRGs and QSOs. I ran the command once and then again, but the code didn't find the existing files and simply overwrote them.

I think we want `select_mock_targets` to look for existing files and only overwrite them if one sets the `--overwrite` option.  Thanks!

**Comment by alxogm** [comment]
@moustakas thanks for reviewing this, yes that was the change intended to do, to not overwrite unless the --overwrite option is present. I think was working, but I can check again.

**Comment by alxogm** [comment]
Hi @moustakas, now I remember. I left the simplest option that was to look for both types of truth files, the bright and dark ones... if one is missing it will redo the pixel. I wrote that in my PR description... I wasn't sure if it was useful to allow to only check for one or the other... It seems it is.. so I'll change it... 

> This PR fixes #582. By replacing the use of
> 
> `desitarget.mock.io` for `desitarget.io.find_target_files` to locate the appropriate dark and bright truthfiles... **it will always look for both files.** I tested adding an option to check for only dark or bright, but I'm not sure how useful this will actually be so I'm just making this simplest PR, and later if I find more useful to have such option I'll open a new issue.
> 
> I've tested this PR in both cases mpi_ and non-mpi

**Comment by moustakas** [comment]
@alxogm any progress on this PR?

**Comment by alxogm** [comment]
> @alxogm any progress on this PR?


Hi, yes I changed it... you can see if it works now for you... I copy here what was happening... 

> Hi @moustakas, now I remember. I left the simplest option that was to look for both types of truth files, the bright and dark ones... if one is missing it will redo the pixel. I wrote that in my PR description... I wasn't sure if it was useful to allow to only check for one or the other... It seems it is.. so I'll change it...
> 
> > This PR fixes #582. By replacing the use of
> > `desitarget.mock.io` for `desitarget.io.find_target_files` to locate the appropriate dark and bright truthfiles... **it will always look for both files.** I tested adding an option to check for only dark or bright, but I'm not sure how useful this will actually be so I'm just making this simplest PR, and later if I find more useful to have such option I'll open a new issue.
> > I've tested this PR in both cases mpi_ and non-mpi

**Comment by moustakas** [comment]
Excellent, this looks great!

**Pull request merged**
