### PR TITLE
Various updates to targeting bits and MTL

### PR DESCRIPTION
**Pull request by geordie666**
This PR makes a range of updates, mostly to how targets are prioritized in MTL. It includes:
- Don't select any `BGS_WISE` targets in the Main Survey.
- Always set BGS targets that have a bad spectroscopic observation (`ZWARN > 0`) to a (very low) priority of `DONE`.
- Add an informational bit for the Main Survey indicating which QSOs are selected with the high-redshift Random Forest (addresses #349 ).
- MWS/BGS joint targets are now driven by the MWS priority _for the second observation_. Unobserved MWS targets will still always have a higher priority than repeat (`MORE_ZGOOD`) BGS targets, but targets that have both MWS and BGS bits set will be driven by the BGS `MORE_ZGOOD` priority rather than by the MWS priority.
- Update the default priorities for reobserving Lyman-alpha QSOs (as described in #486, which this addresses).

### CODE REVIEW

**Comment by geordie666** [comment]
@apcooper: I'd appreciate your review on whether I've messed up MTL for the MWS in this PR. In `master`, every time a joint BGS/MWS target requested an additional observation it would be at the (higher) MWS initial (`UNOBS`) priority. This would mean that for a fiber-collided pair of BGS targets, one of which was also an MWS target, we'd always observe the joint BGS/MWS target, _even if `ZWARN > 0` for the spectroscopic observation_. The way I've set things up in this branch, we'd instead split observations between the MWS/BGS joint target and the BGS target. I'm happy to change back to the behavior in `master` if you think my new approach is incorrect, or we could make new-and-improved choices for the `MORE_ZGOOD` and `MORE_ZWARN` priorities for MWS targets.

@Cyeche: It would be great if you can confirm that my new "informational" bit indicating which QSO targets are from the _high-z_ RF doesn't affect target selection behavior for the QSOs at all (other than turning on one new informational bit).

@michaelJwilson: Can you confirm that these are the two changes requested by the BGS Working Group that you communicated to me:
1. Turning off `BGS_WISE`.
2. Ensuring repeat observations of BGS targets with `ZWARN>0` are always set to a very low priority (i.e. are effectively `DONE`).

**Comment by michaelJwilson** [comment]
@geordie666 I understand the intention to be the correct one.  I'll ask for any last minute objections at the BGS telecon on Friday and hopefully have a look at the implementation aswell.

**Comment by apcooper** [comment]
Just to add:

> we could make new-and-improved choices for the MORE_ZGOOD and MORE_ZWARN priorities for MWS targets.

This is probably something we (MWS) will want to look into again in the near future, as we shift attention from SV planning back to the main survey.

**Comment by geordie666** [comment]
Thanks for your review, @apcooper. I was most concerned that I was messing up the MWS behavior in some way, so I'll merge this tomorrow even if I receive no further reviews.

**Comment by michaelJwilson** [comment]
@geordie666 I finally got an opportunity to bring this up at a regular telecon.  

--  BGS_WISE should be parked. 
--  BGS does not want to re-observe failed redshifts, as this couples the assignment probabilities to redshifting & target type, which leads to a much harder correction.  

So yes to both.  I think 'effectively done' is fine in terms of implementation, but really we want done done.

**Comment by geordie666** [comment]
Thanks @michaelJwilson. I believe that both of those BGS requests were implemented in this (now merged) PR. Of course, if you find otherwise, or want additional different behavior, let me know!

**Pull request merged**
