### PR TITLE
Pixel-based creation of blank sky locations

### PR DESCRIPTION
**Pull request by geordie666**
Generate sky locations using pixel-level `blob` maps from the Legacy Surveys imaging. Includes:
   * Significant update of `desitarget.skyfibers`
   * Adds `desitarget.skyutilities.astrometry` to remove any dependency on`astrometry.net`.
   * Adds `desitarget.skyutilities.legacypipe` to remove any dependency on `legacypipe`. 
   * Grids sky locations by applying a binary erosion algorithm to imaging blob maps.
   * Sinks apertures at the resulting sky locations to derive flux estimates.
   * Sets the `BAD_SKY` bit via high flux levels in those apertures, instead of by object proximity.
   * Adds `desitarget.skyfibers.bundle_bricks` to write a slurm script for parallelization.
   * Parallelizes via HEALPixels and runs in a few hours on interactive nodes.
   * Includes a `select_skies` binary to run from the command line.
   * Includes a `gather_skies` binary to collect results from parallelization.
   * Adds functionality to plot good/bad skies against the backdrop of Legacy Survey images.

Here are some results for a brick that is in a "good" area of the imaging:
skies-1462p367-grz
and for a brick in a region that's up against a CCD edge and has minimal coverage:
skies-0556p332-z

I'm out of time on coding this week, but I don't want to waste time on merging what is a lengthy update to the codebase, so I pledge to write unit tests this Friday or over the weekend.

I'm requesting reviews from: 

@sbailey; please, in particular, look at these lines of code:
https://github.com/desihub/desitarget/blob/ADMpixskies/py/desitarget/skyfibers.py#L189-L194
and decide if that is the correct logic for assigning a "bad" sky location (i.e. do we want to demand things are good in every band, or just pick one band)

@dstndstn; please check that I haven't misappropriated anything in:
https://github.com/desihub/desitarget/tree/ADMpixskies/py/desitarget/skyutilities/astrometry
or
https://github.com/desihub/desitarget/tree/ADMpixskies/py/desitarget/skyutilities/legacypipe
and that the licensing fairly reflects our use of these code snippets.

### CODE REVIEW

**Comment by geordie666** [comment]
Conflicts in the `changes.rst` file are easy to resolve. Once the reviewers have signed off on the code changes, I'll resolve them in the web editor before merging.

**Comment by geordie666** [comment]
@sbailey: also, an informative command if you want to try to run this yourself is:
```
select_skies /global/project/projectdirs/cosmo/data/legacysurvey/dr6 $CSCRATCH --bundlebricks 14000
```

**Comment by geordie666** [comment]
Thanks @dstndstn, I'll copy and paste the actual licenses over instead of linking to them.

I checked the `ring_unique` function explicitly when I was porting the code to `astropy` and I obtained the exact same values using the 0-index specification as `astrometry.net` obtains for the 1-index specification (give or take 1e16 in floating point variation). So, I'm confident that the function is expressed correctly. It's possible that `astropy` internally shifts everything to the `numpy` convention.

**Comment by dstndstn** [comment]
Okay, that's good to know about the WCS routines!

It's up to you, but I think I would just say something like

# This code is from astrometry.net:
https://github.com/dstndstn/astrometry.net
# as of version 0.73 (git hash ######). This file (util/fits.py) is
licensed under the BSD-3 license.

**Comment by geordie666** [comment]
Cool...I'll use your suggested language, which is nice and compact.

**Comment by sbailey** [comment]
Ugh about legacypipe being GPL.  We can't legally copy-and-paste that code into desitarget without also making desitarget GPL, which runs the risk of getting LBL lawyers involved.  If possible, a better route would be to have the authors of legacypipe agree to change its license to BSD, in which case we can easily copy-with-attribution and move on.

**Comment by dstndstn** [comment]
Yes, let me see if I can quickly get that agreement from the authors and
relicense it.

**Comment by sbailey** [comment]
@geordie666 which desi environment were you using at NERSC when testing this?  Using "source /project/projectdirs/desi/software/desi_environment.sh master" plus swapping to this branch of desitarget, I hit a photutils+astropy incompatibility:
```
[cori06 desitarget] select_skies -h
Traceback (most recent call last):
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/bin/select_skies", line 6, in <module>
    from desitarget.skyfibers import select_skies, density_of_sky_fibers
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/skyfibers.py", line 15, in <module>
    import photutils
  File "/global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/conda/lib/python3.6/site-packages/photutils/__init__.py", line 17, in <module>
    from .background import *      # noqa
  File "/global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/conda/lib/python3.6/site-packages/photutils/background/__init__.py", line 7, in <module>
    from .core import *             # noqa
  File "/global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/conda/lib/python3.6/site-packages/photutils/background/core.py", line 15, in <module>
    from astropy.stats import (SigmaClip, biweight_location, biweight_scale,
ImportError: cannot import name 'SigmaClip'
```

Unfortunately photutils/0.4 requires astropy/2.x, but in desiconda 20180130-1.2.4-spec (current default) we have the incompatible combination photutils/0.4 plus astropy/1.3.3.  Our older desiconda 20170613-1.1.4-spectro has a compatible set photutils/0.3.2 + astropy/1.3.3, but that desiconda has other problems (numpy crashes...)

photutils wasn't on my radar screen of known dependencies.  Did this come in via astropy, or are we purposefully installing it additionally?  How critical is your dependency on it?

We could cut a new version of desiconda with astropy=2 if needed, but that becomes a rather big required upgrade to our environment to bring in this PR.

**Comment by geordie666** [comment]
It looks like I was testing on the older desiconda `20170613-1.1.4-spectro`.

`numpy` isn't crashing for me though with that environment, though:

```
In [4]: numpy.version
Out[4]: <module 'numpy.version' from '/global/common/edison/contrib/desi/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/numpy/version.py'>
In [5]: import photutils
In [6]: photutils.version
Out[7]: <module 'photutils.version' from '/global/common/edison/contrib/desi/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/photutils/version.py'>
In [8]: import astropy
In [9]: astropy.version
Out[9]: <module 'astropy.version' from '/global/common/edison/contrib/desi/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/astropy/version.py'>
``` 

`photutils` is used in the code to perform aperture photometry at sky locations. I can turn that feature off, or dig around for another piece of code to perform aperture photometry. I do think we'll want that feature, though.

**Comment by dstndstn** [comment]
FYI the legacypipe relicensing to BSD 3-clause is complete.

**Comment by sbailey** [comment]
Thanks for legacypipe relicensing; we'll need to update the reference in here too.

I'm building a test desiconda release to test this with astropy 2.x.  That's a bit overkill; I could have tested with a conda environment + upgrade, but if we do merge this will need a new desiconda release anyway for it to work.

**Comment by dstndstn** [comment]
Ooh, if you're going to do a new desiconda build, could I sneak in the
newest Astrometry.net and Tractor releases?

https://github.com/dstndstn/astrometry.net/releases/tag/0.74
https://github.com/dstndstn/tractor/releases/tag/dr7.0

**Comment by sbailey** [comment]
I tried testing this with a new desiconda build in
```
module use /global/cscratch1/sd/sjbailey/desi/desiconda/modulefiles
module load desiconda
```
with the commands
```
srun -N 1 select_skies /global/project/projectdirs/cosmo/data/legacysurvey/dr6 $CSCRATCH/dr6-skies-hp-309,313,325,569,758.fits --numproc 64 --nside 16 --healpixels 309,313,325,569,758
```
It died with the traceback below.
```
INFO:select_skies:72:<module>: Generating 144 sky positions in each brick
INFO:skyfibers.py:832:select_skies: Processing bricks in (nside=16, pixel numbers=[309, 313, 325, 569, 758]) HEALPixels
INFO:skyfibers.py:836:select_skies: Processing 791 bricks that have observations from DR at /global/project/projectdirs/cosmo/data/legacysurvey/dr6...t = 0.5s
Running on Node nid00058
Traceback (most recent call last):
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/internal/sharedmem.py", line 674, in map
    capsule = pg.get(R)
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/internal/sharedmem.py", line 384, in get
    raise StopProcessGroup
desitarget.internal.sharedmem.StopProcessGroup: StopProcessGroup

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/bin/select_skies", line 79, in <module>
    bundlebricks=ns.bundlebricks)
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/skyfibers.py", line 869, in select_skies
    skies = pool.map(_get_skies, bricknames, reduce=_update_status)
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/internal/sharedmem.py", line 678, in map
    raise pg.get_exception()
desitarget.internal.sharedmem.SlaveException: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
Traceback (most recent call last):
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/internal/sharedmem.py", line 265, in _slaveMain
    self.main(self, *self.args)
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/internal/sharedmem.py", line 563, in _main
    r = realfunc(work)
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/internal/sharedmem.py", line 629, in realfunc
    else: return func(i)
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/skyfibers.py", line 849, in _get_skies
    badskyflux=badskyflux, write=writebricks)
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/skyfibers.py", line 163, in make_skies_for_a_brick
    apertures_arcsec=apertures_arcsec)
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/skyfibers.py", line 312, in sky_fibers_for_brick
    x,y,blobdist = sky_fiber_locations(goodpix, gridsize=gridsize)
  File "/global/cscratch1/sd/sjbailey/desi/code/desitarget/py/desitarget/skyfibers.py", line 393, in sky_fiber_locations
    from scipy.ndimage.morphology import binary_dilation, binary_erosion
  File "/global/cscratch1/sd/sjbailey/desi/desiconda/conda/lib/python3.6/site-packages/scipy/ndimage/__init__.py", line 164, in <module>
    from .measurements import *
  File "/global/cscratch1/sd/sjbailey/desi/desiconda/conda/lib/python3.6/site-packages/scipy/ndimage/measurements.py", line 36, in <module>
    from . import _ni_label
  File "__init__.pxd", line 164, in init _ni_label
RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88

srun: error: nid00058: task 0: Exited with exit code 1
srun: Terminating job step 12129770.5
```

That desiconda installation has
* scipy/1.0.1
* numpy/1.13.3

Some quick googling (e.g. [here](https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility)) indicates that that RuntimeWarning should be harmless, but do you perhaps have a leftover filter to treat warnings as errors?

**Comment by weaverba137** [comment]
`RuntimeWarning` did not cause this error.  See the line that says "During handling of the above exception, another exception occurred:"

The "above exception" was `desitarget.internal.sharedmem.StopProcessGroup`.

**Pull request merged**
