### PR TITLE
Minimal hack to get desitarget running from refcat workaround.

### PR DESCRIPTION
**Pull request by michaelJwilson**
Minimal hack to get desitarget running from refcat workaround.  Likely not an acceptable approach, but illustrates what needs fixed.  Maybe useful in the meantime.  Runs to completion.

### CODE REVIEW

**Comment by weaverba137** [comment]
I know this PR is just illustrative, but please clean up the extraneous files like `#cuts.py#`.  You may want to adjust your `.gitignore` file to prevent git from interpreting these files as important.

**Comment by geordie666** [comment]
As I mentioned over on `fiberassign`: I think I have a different fix that corrects the `try/except` clause that is actually failing, instead of modifying the mocks (treats the cause not the symptoms).

I'll try to implement that later today. In the meantime, though, @michaelJwilson's fix should be useful for anyone that needs to process things in the short-term. Just, don't merge this PR!

**Comment by sbailey** [comment]
Following up on @weaverba137's request, we'll want to BFG repo clean the extraneous fits files:
* py/desitarget/mock/0/1/bright/targets-bright-16-1.fits
* py/desitarget/mock/0/1/bright/truth-bright-16-1.fits
* py/desitarget/mock/0/1/dark/targets-dark-16-1.fits
* py/desitarget/mock/0/1/dark/truth-dark-16-1.fits

and either git remove or fully BFG repo clean:
* #cuts.py#
* #select_mock_targets.yaml#
* run.sh

@michaelJwilson let's chat in person about your git workflow to avoid these accidentally adds in the future.

**Comment by geordie666** [comment]
@sbailey: I'll BFG repo-clean those files, too. Today, I hope.

**Comment by geordie666** [comment]
This has been supplanted by PR #588. This PR (#586) should eventually be closed without merging.

**Pull request closed without merging**
