### PR TITLE
add contaminants to mock.build.targets_truth and fix lots of small issues

### PR DESCRIPTION
**Pull request by moustakas**
This is an incremental PR to address some of the issues raised in #169.  It includes a first  (preliminary) effort of including contaminants and also adds many small improvements and fixes to `mock.build.targets_truth` (and the code it calls).

Contaminants identified using a new set of targeting bits, which I found to be necessary because of the extensive overlap between various target classes and contaminants.  

There's also a preliminary [notebook](https://github.com/desihub/desitarget/blob/qamock/doc/nb/mock-qa.ipynb) which generates some much-needed QA.  There are still many issues we'll want to fix (and which I'll document elsewhere) but this should be sufficient for the 2% sprint.

Still ToDo before merging:

* This depends on https://github.com/desihub/desisim/pull/234 so we should merge that first.
* I still need to test this at NERSC and check the time / memory usage, but I think it has improved.

### CODE REVIEW

**Comment by moustakas** [comment]
Following up on the conversation on the telecon -- this shouldn't be merged quite yet until I've tested and timed at NERSC.  There's also some memory savings I'd like to try to implement.

**Comment by sbailey** [comment]
desihub/desisim#234 has been merged, so I think dependencies are in place for this.  This code looks fine.  Go ahead and merge when you are satisfied with NERSC tests.

**Comment by sbailey** [comment]
Also, please update doc/changes.rst before merging.

**Comment by moustakas** [comment]
This is now reasonably functional so I'm merging now.

**Pull request merged**
