### PR TITLE
density fluctuations models

### PR DESCRIPTION
**Pull request by forero**
Code to measure and characterize density fluctuations in DECALS data.

### CODE REVIEW

**Comment by forero** [comment]
@geordie666 is this ready to merge? I would like to make the mock developments in a new branch once this is in master.

**Comment by geordie666** [comment]
@forero the QA branch is stable and doesn't interfere with the functioning of any other parts of desitarget, so somebody (ideally not the author, me!) can merge it.

It doesn't have unit tests etc. But, I'll try to add some at a later date.

**Comment by moustakas** [comment]
@geordie666 I haven't looked at the code in detail, but would it be possible to include the typical depth or variance in the WISE photometry in each brick?  I need this in order to be able to perturb the "perfect" WISE fluxes produced by the spectra assigned to the mocks in #136.

**Comment by geordie666** [comment]
I don't _think_ that will be hard. I'll try to get to that this week.

**Comment by geordie666** [comment]
@moustakas I started to look at this and I think it _is_ hard, in actuality. To populate depths, I was using @dstndstn's per-brick depth files, e.g., see the documentation for dr3-depth-summary.fits.gz at:
http://faraday.uwyo.edu/~admyers/scratch/legacysurvey/output/dr3/files/
I don't think there's a similar product for WISE?

**Pull request merged**
