### PR TITLE
Dr9 shift

### PR DESCRIPTION
**Pull request by Cyeche**
Tune the photometry shifts between South and North Photometry for DR9
![North_vs_South_dr9]
(https://user-images.githubusercontent.com/22040400/94370210-f6564f00-00ee-11eb-85b3-e9529962bd20.png)

### CODE REVIEW

**Comment by geordie666** [comment]
Thanks, @Cyeche this looks simple enough for you to self-merge once tests pass.

Ideally, you'd update the `doc/changes.rst` file to list this PR before merging. But, I can also update that in my work-in-progress PR, so it's not critical.

(I see you also already updated the wiki. Thanks!)

**Comment by Cyeche** [comment]
Thanks!

Could please update doc/changes.rst.

**Comment by weaverba137** [comment]
Is there a reason the branch `dr9_shift` has not been deleted?

**Comment by geordie666** [comment]
Thanks for the cleanup @weaverba137.

**Pull request merged**
