### PR TITLE
update lrg sv selection: relaxed zfiber limit and IR sliding cut

### PR DESCRIPTION
**Pull request by rongpu**
@geordie666 This PR includes the following changes to the LRG SV selection:

1. the zfibermag faint limit is changed from 21.6 to 21.9
2. for the IR selection, objects with r-W1>3.1 are not subjected to the sliding cut; the added targets are mostly at high (z>~0.7) redshifts

These changes are based on conclusions from the telecon discussion yesterday (10/9/2019).

### CODE REVIEW

**Comment by geordie666** [comment]
@rongpu: This looks fine, but please, also:

1. Update the [SV targeting wiki](https://desi.lbl.gov/trac/wiki/TargetSelectionWG/SurveyValidation)
2. Update the [Changes file](https://github.com/rongpu/desitarget/blob/lrg_updates/doc/changes.rst)

You won't be able to do 1. until after the power returns at NERSC. But, I think unit tests will fail until then, anyway.

**Comment by rongpu** [comment]
@geordie666: Thanks. I've updated the changes file. I will update the wiki when the servers are back.

**Comment by geordie666** [comment]
@rongpu: One more thing...in the changes file, you need to add a link to your PR, otherwise the "build sphinx" [unit tests](https://travis-ci.org/desihub/desitarget/jobs/596377108) will fail.

See [the lines here](https://github.com/desihub/desitarget/compare/master...rongpu:lrg_updates#diff-7ef3733acbbb4d945fc98255afcf1ac9L60-L68) and add something like them [here](https://github.com/desihub/desitarget/compare/master...rongpu:lrg_updates#diff-7ef3733acbbb4d945fc98255afcf1ac9R11) for PR #550 under version 0.33.1.

**Comment by rongpu** [comment]
@geordie666 I had already added the link ``[`PR #550`_]`` in the changes file, but it is not working properly and I'm not sure why.

**Comment by geordie666** [comment]
@rongpu: Don't worry...I'll just take over this branch and commit the necessary changes before merging it.

**Comment by rongpu** [comment]
@geordie666 I have updated the wiki (https://desi.lbl.gov/trac/wiki/TargetSelectionWG/SurveyValidation) with these changes

**Comment by geordie666** [comment]
@rongpu: Thanks, I'll merge this soon.

**Pull request merged**
