### PR TITLE
Add scaffold for documentation.

### PR DESCRIPTION
**Pull request by rainwoodman**
This pull request sets up the documentation more or less following desispec / desi-template.

An additional script apidoc.sh generates the automatically documentation files.

Note that the directory name is docs, since I find .gitignore contains docs/_build but do not contains doc/_build . If it is necessary we shall rename the directory and .gitignore entry as well.

### CODE REVIEW

**Comment by weaverba137** [comment]
When the directory structure and .gitignore are in conflict, you should change .gitignore.

Documents should be built by `python setup.py build_sphinx` and no other method.

**Comment by rainwoodman** [comment]
I renamed the directory to doc/ but setup.py build_sphinx is not building anything...

**Comment by rainwoodman** [comment]
I see that the default doc directory needs to be overridden. 

Is 'setup.cfg' (like here) the right way to do this? 

apidoc.sh generates a few .rst files. It does not overlap with the functionality of build_sphinx.

**Comment by weaverba137** [comment]
I think at this point it would be best for you to just wait until desitemplate is updated, rather than make an unofficial change, and then have it not follow the template once it is finalized.

**Comment by rainwoodman** [comment]
Sure. shall we move the setup.cfg discussion back to desitemplate?

**Comment by rainwoodman** [comment]
I have just updated the documents against the master branch. What we have here is rather close to desitemplate, and it is hard to see how it would diverge siginifcantly from the template.

Shall we merge it before it get out of sync again?

Who shall be responsible push docs to github.io?

**Comment by sbailey** [comment]
I'll merge this now.  @weaverba137 set up the Travis tests and automagical github -> readthedocs for other packages.  @rainwoodman could you set that up for desitarget in a separate PR?  It would be good for us to make sure that more than one person can do this in the context of desi.  Thanks.

**Comment by weaverba137** [comment]
>  @weaverba137 set up the Travis tests and automagical github -> readthedocs for other packages. 

Is that a statement or a command?

**Comment by rainwoodman** [comment]
@weaverba137 Could you point to me an example github->readthedocs? 
Does it involve some push hooks? 

I am filing another PR that migrates the conf.py and Makefile of desitemplate -- but seems like them alone can't really do the magic.

**Comment by dstndstn** [comment]
Just sign up for a readthedocs account and it's pretty straightforward.

**Comment by weaverba137** [comment]
Hello y'all,

Please see my recent email to desi-data.

Kia ora koutou,
Benjamin Alan Weaver

On Mon, Nov 30, 2015 at 2:17 PM, Dustin Lang <notifications@github.com>
wrote:

> Just sign up for a readthedocs account and it's pretty straightforward.
>
>
> On Mon, Nov 30, 2015 at 4:16 PM, Yu Feng <notifications@github.com> wrote:
>
> > @weaverba137 <https://github.com/weaverba137> Could you point to me an
> > example github->readthedocs?
> > Does it involve some push hooks?
> >
> > I am filing another PR that migrates the conf.py and Makefile of
> > desitemplate -- but seems like them alone can't really do the magic.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/desihub/desitarget/pull/5#issuecomment-160729931>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/desihub/desitarget/pull/5#issuecomment-160730119>.
>



-- 
a.k.a. The Dream Weaver

Outside of a dog, a book is man's best friend. Inside of a dog it's too
dark to read.
  --Groucho Marx

**Pull request merged**
