### PR TITLE
Add OBSCONDITIONS to target files.

### PR DESCRIPTION
**Pull request by geordie666**
This PR adds the `OBSCONDITIONS` bitmask to output target files, instead of it being added in MTL. As part of this modification, it also:

- Splits target files explicitly into two sub-directories corresponding to "bright" and "graydark" surveys.
- Defaults to splitting target files in such a manner for SV and the Main Survey (not for commissioning).

Coincidentally, this PR:
- Adds an informational bit for supplemental sky locations.

### CODE REVIEW

**Comment by geordie666** [comment]
@sbailey: Last week we decided that the idea of adding `OBSCONDITIONS` to the target files and splitting the targets into separate bright/graydark files had finally had time to percolate and so we should go ahead and do it. You noted that we should retain the bright-time targeting bits in the dark-time file and vice-versa for easier tracking of matching bright/dark targets. This PR makes those updates.

However, this done _not_ solve issues such as #400, or the issue that quasar targets can be set to have 4 observations in bright time. This is _because_ we retain the bright-time targeting bits in the dark-time file and vice-versa, and MTL operates on the targeting bits, oblivious to the `OBSCONDITIONS`.

If we want to ensure that only bright-time `PRIORITY`/`NUMOBS_MORE` decisions are applied to bright-time objects (and dark-time `PRIORITY`/`NUMOBS_MORE` decisions to dark-time objects) then I think there are only two solutions:

1. As also noted in #400, give MTL some knowledge of the desired `OBSCONDITIONS` that it can use to follow different logic for setting `PRIORITY`/`NUMOBS_MORE`.

2. Only write out the dark-time targeting bits to the dark-time file and only write out the bright-time targeting bits to the bright-time file. Any knowledge of a match would be retained in `TARGETID` but post-processing would be required to look for bright-time targets with dark-time spectra and vice-versa. We would also have to deprecate any ` {obsconditions: BRIGHT|GRAY|DARK}` choices for bright-time targets and fix them to only be observed in ` {obsconditions: BRIGHT}`.

Advice and guidance?

**Comment by sbailey** [comment]
I think I prefer your option (1):

> 1. As also noted in #400, give MTL some knowledge of the desired OBSCONDITIONS that it can use to follow different logic for setting PRIORITY/NUMOBS_MORE.

Would it be meaningful to encode in a header keyword which OBSCONDITIONS each target file is for, and have MTL use that instead of trusting the user to remember (while still providing the ability to override it)?  Or otherwise make mtl require explicit obsconditions and fail if the user doesn't provide it?  i.e. let's avoid a situation where the default arguments result in the wrong behavior.

**Comment by geordie666** [comment]
That would be meaningful, but aren't people passing tables/arrays to MTL rather than files?

I'll make it explicit that this needs to be passed (and fail without it), but trust the user to have read the appropriate header keyword (which is mostly coded up already [in the current PR](https://github.com/desihub/desitarget/blob/ADM-add-OBSCON/py/desitarget/io.py#L324-L336).

Can we merge this and I'll get back to fixing issue #400 later? I've started to work on other things while this PR was dangling. It's a complete PR, as it has improved MTL without addressing #400.

**Comment by sbailey** [comment]
Good point.  This PR doesn't fix everything related to OBSCONDITIONS but it is a step in the right direction without a corresponding step backwards, so ok to merge it.

**Pull request merged**
