### PR TITLE
Bgs target

### PR DESCRIPTION
**Pull request by qmxp55**
New BGS target selection

### CODE REVIEW

**Comment by sbailey** [comment]
This has some non-trivial merge conflicts in cuts.py and QA.py, so @moustakas and @geordie666 please review and merge carefully.  I know that @geordie666 is on vacation; we may want to wait for him to get back unless John is completely familiar with the situation here.

**Comment by moustakas** [comment]
I can start the review.

@qmxp55 thanks for this PR!  To start, can you please merge `desitarget/master` branch into your branch, and resolve all the conflicts.  E.g., something like this should hopefully work--
```
cd /path/to/your/fork/of/desitarget
git fetch upstream
git checkout bgs_target
git merge upstream/master
```
Then commit your changes and I can start looking into the code changes.

And second, it looks like you've updated the wiki, but can you confirm (here) that that page has all the desired changes which have been signed off on and validated by the Target Selection WG?
  https://desi.lbl.gov/trac/wiki/TargetSelectionWG/TargetSelection#BrightGalaxySurveyBGS

**Comment by moustakas** [comment]
Travis tests are failing because this selection brings in a new dependence on `FRACIN_[G,R,Z]`, which we do not propagate into the sweeps.  We should also take this opportunity to remove `ALLMASK_[G,R,Z]` from the sweeps, which I *think* we don't use anymore.

@qmxp55, see if you can fix any of the other failing tests and I'll continue to review and test the actual code.

BTW, I haven't seen you send a note to @desi-targets announcing this new selection, but that would be good to do (and be sure to point to the wiki page you updated).  If you have a short TechNote or set of slides to share with the group that would be great, too.

**Comment by sbailey** [comment]
Please don't merge any PRs that would change the required inputs or output format for target selection, until after the collaboration meeting.  OK to have this in a branch with documentation about its improvements, but I'm trying to limit the number of moving parts as we finalize the overdue 18.9 release.  Thanks.

**Comment by geordie666** [comment]
I ended up working on this PR in a separate branch and it is now https://github.com/desihub/desitarget/pull/402. So, I'm closing this PR.

**Pull request closed without merging**
