### PR TITLE
 Update Commissioning and Main Survey target classes.

### PR DESCRIPTION
**Pull request by geordie666**
Includes:
- New `SV0_WD` and `SV0_STD_FAINT` target classes for commissioning.
- Mild updates to the `SV0_BGS` and `SV0_MWS` target classes for commissioning.
- New `BGS_FAINT_HIP` Main Survey class. These are `BGS_FAINT` targets at the `BGS_BRIGHT` priority.
- Explicit checking on `ASTROMETRIC_PARAMS_SOLVED` for MWS targets that use proper motion and parallax.
- Adds a 3-sigma parallax slop in the `MWS_MAIN` survey target class.

Should address #522.

### CODE REVIEW

**Comment by sbailey** [comment]
Looks like this also drops the BGS_KNOWN_XXX bits.  Any comments on that?  e.g. will those be brought in via secondary targets instead as needed?  Otherwise looks fine; I fixed merge conflicts in changes.rst, which has triggered another round of tests.

**Comment by geordie666** [comment]
Yes, secondary targets is exactly the way to bring in KNOWN objects. My use cases for secondary targets are:

(1) Not based on sources in the sweeps files.
(1a Outside of the footprint).
(2) Based on an RA/Dec cross-match.

The `BGS_KNOWN` bits aren't defined anywhere, as far as I can tell. So, I decided that they were probably just placeholders.

**Comment by sbailey** [comment]
Sounds good.  documentation build tests are failing due to docs.astropy.org being down (522, meaning sort of up but not really).  Will retry later.  OK to merge now if that is a blocking factor for proceeding with other work.

**Comment by geordie666** [comment]
Let's hold off merging this for a day. The MWS folks may not want one of the flags I've added, but I'll change that tomorrow if needed (it's a one-liner).

**Comment by sbailey** [comment]
Two days have passed without an outcry, so merging now.  We can revert later if needed, since I'm sure that there are other target cuts coming down the pipe too.

**Pull request merged**
