### PR TITLE
Additional data model updates for DR8

### PR DESCRIPTION
**Pull request by geordie666**
This PR updates a few remaining elements of the data model to run on the DR8 imaging surveys. Includes:

- Add the `WISEMASK_W1` and `WISEMASK_W2` bitmasks to the random catalogs.
- Deprecate `BRIGHTBLOB` in favor of using `MASKBITS` for targets.

The second update is necessary because `MASKBITS` should be identical for the targets and for the randoms, whereas `BRIGHTBLOB` would be marginally inconsistent between targets and randoms. See #491, which this PR should address.

### CODE REVIEW

**Comment by geordie666** [comment]
@moustakas: as I know you're about to start working on the mocks again, I wanted to push the (hopefully) final data model changes for DR8.

These will, in typical fashion, break `select_mock_targets`, although I think you probably just have to change occurrences of `BRIGHTBLOB` to `MASKBITS`.

If you were mocking up `BRIGHTBLOB` to be `2**0` for the mocks, note that you'll now have to make it `2**1`, or bit-shift it as I did [here](https://github.com/desihub/desitarget/blob/ADM-more-DR8-updates/py/desitarget/io.py#L252-L254).

**Comment by geordie666** [comment]
@moustakas: I also restored the meaning of the `qso_selection==colorcuts` option for the SV cuts. It should now be straightforward to bypass the QSO Random Forest selection when creating SV mocks, e.g.:

```
select_targets(infiles, survey='sv1', qso_selection='colorcuts', ..., ...)
```

**Comment by moustakas** [comment]
Thanks @geordie666.  The targeting catalogs do not contain the (new) `PSFDEPTH_W[1,2]` columns -- do we want these?

**Comment by geordie666** [comment]
`PSFDEPTH_G, R, Z` and `GALDEPTH_G, R, Z` are not used for the targets. They *are* produced in the random catalogs, and then those randoms are used in QA, but they aren't touched in the target selection itself.

So, guessing that `PSFDEPTH_W1, W2` will be the same, and with a view to not further unnecessarily expanding the target files, I'm not going to propagate `PSFDEPTH_W1, W2`. For now.

**Comment by sbailey** [comment]
Is this PR backwards compatible with running TS on DR6 and DR7, in addition to supporting the data model changes for DR8?

I'm ok with not including PSFDEPTH_* in this round, but we should revisit that in the broader picture of what should (not) be included.  The original guidelines for what should be included in TS:
1. columns needed for provenance (BRICKID, TARGETID, RELEASE, ...)
2. columns used by target selection
3. columns likely needed for key downstream analyses (QA and/or science)

PSFDEPTH_* seems in the (3) category.  Of course this was before the TS files ballooned, so now were revisiting what *really* needs to be included.

**Comment by geordie666** [comment]
Trying to condense a bunch of discussion on-and-off-list into a conclusion:

I'm confident that this PR IS backwards-compatible with DR6 and DR7 files (I'll check one last time before merging). And, I won't propagate propagate `PSFDEPTH_W1, W2` for targeting, but I will add them to the sweeps in the legacypipe repo.

@moustakas: Unless you disagree I'll merge #493, #494, and #496 in an hour or two after running a few final tests.

**Pull request merged**
