### PR TITLE
Update the LRG selection for SV3

### PR DESCRIPTION
**Pull request by rongpu**

### CODE REVIEW

**Comment by geordie666** [comment]
@rongpu: Thanks, these new cuts look straightforward, and I see you already updated the wiki. I'm happy for you to merge this branch when you're ready (or I'll merge it in an hour or so).

My only question would be bright-end cuts? I know that we had a few (but only a very few) quite-bright LRGs in the SV2 target files. Has that been handled?

**Comment by rongpu** [comment]
@geordie666 I wasn't aware that there are very bright LRGs in SV2. I thought the Gaia G>18 cut has already rejected all of them (and the same cut is also included for SV3). Could you point me to specific tile(s) that has the bright LRGs so I can check? Thanks.

**Comment by geordie666** [comment]
@rongpu: Here are some examples (at NERSC):
```
from desitarget.targetmask import desi_mask 
import fitsio  
import numpy as np  
from glob import glob 
fns = glob("/global/cfs/cdirs/desi/target/catalogs/dr9/0.53.0/targets/sv2/resolve/dark/*fits") 
brightlrgs = [] 
for fn in fns: 
     a = fitsio.read(fn) 
     ii = a["SV2_DESI_TARGET"] & desi_mask["LRG"] != 0 
     ii &= 22.5-2.5*np.log10(a["FLUX_R"]) < 15 
     brightlrgs.append(a[ii]) 
brightlrgs = np.concatenate(brightlrgs) 
for bl in brightlrgs: 
     print(desi_mask.names(bl["SV2_DESI_TARGET"]), 22.5-2.5*np.log10(bl["FLUX_R"]))  
                                                                                                                                                                                                
['LRG', 'LRG_NORTH'] 14.252433180809021
['LRG', 'LRG_NORTH'] 14.059534072875977
['LRG', 'LRG_NORTH'] 14.790923595428467
['LRG', 'LRG_NORTH'] 14.491814374923706
```

**Comment by rongpu** [comment]
@geordie666 Thanks! I realized that these are bright stars missing from GAIA DR2. I had originally proposed a zfiber>16 cut to remove them, but somehow forgot to implement it. I will add the cut to the PR now.

**Comment by rongpu** [comment]
@geordie666 I have added the fix. The branch is ready to merge now.

**Comment by deisenstein** [comment]
A question from the paranoid:  should we be making bright cuts with
FIBERFLUX or FIBERTOTFLUX?  It probably almost never matters, but maybe it
should be the latter?

**Comment by geordie666** [comment]
@deisenstein: For galaxies I'd agree tht we want to make bright end cuts in `FIBERTOTFLUX`. But, I'm going to merge this to make continued progress. We'll have the option to make another round of (minor) updates once we've tests fiberassign/priorities.

**Pull request merged**
