### PR TITLE
Qso dr8

### PR DESCRIPTION
**Pull request by Cyeche**
- Tune of baseline QSP selection for DR8
- Add bits for SV (Split for 4PASS and 8PASS, lowz/highz)

### CODE REVIEW

**Comment by geordie666** [comment]
@Cyeche: I incorporated all of the bit definitions that we talked about in Salt Lake City and offline into the SV yaml file. Most of my other changes are cosmetic (for code style and documentation).

If you agree that I haven't broken anything, and that the new SV bit definitions look correct, then I'm happy to merge this once tests pass.

If it helps, I ran the new SV selections on DR8 and the resulting files are here:

```
/global/cscratch1/sd/adamyers/targets-dr8b-90prime-mosaic-sweep2-PR489.fits
/global/cscratch1/sd/adamyers/targets-dr8b-decam-sweep2-PR489.fits
```

Also, thanks for simplifying the N/S logic in the Random Forest functions, which should address #482.

**Comment by Cyeche** [comment]
@geordie666 @nathalieGit 
The current version of bit definitions is OK. It is what we decided last week in SLC. 

Today we tuned again the SV and nominal selection to be close to our target budget. A final tuning of north and south will be done once we have the final DR8.

**Comment by geordie666** [comment]
@Cyeche: This looks good to me. Shall we merge this so it doesn't go stale and you can tune things again in a different PR when we have DR8 in hand?

Thanks for contributing the code directly yourself. It saves me a bunch of time, and I really appreciate it.

**Comment by Cyeche** [comment]
@geordie666 
Merged!

**Pull request merged**
