### PR TITLE
Updates to the ELG and MWS target classes and the selection of sky locations

### PR DESCRIPTION
**Pull request by geordie666**
Modify several target classes, mostly to reflect changes on the main survey targeting wiki. Includes:

- Refactor of the `ELG` and `MWS_MAIN` selection algorithms to better split color cuts/masking and north/south.
- Update of the `ELG` and `MWS_MAIN` selection cuts. In particular, the ELG masking logic now requires `BRIGHTSTARINBLOB`.
- Change `MWS_WD` targets to have a priority higher than all of the `BGS` target classes.
- Set sky locations to `BAD` only if *both* of the g-band and the r-band are missing.

Should fix issues https://github.com/desihub/desitarget/issues/348 and https://github.com/desihub/desitarget/issues/399.

### CODE REVIEW

**Comment by moustakas** [comment]
Can we get clarification from the Targeting WG about the use of cuts on `allmask_[g,r,z]` for "north" ELGs but not for "south" ELGs?  Actually, it looks like the code applies the `allmask` to both north and south ELG targets, which doesn't quite match the wiki.

Also, for the sake of clarity I wonder if we can combine the g- and r-band magnitude cuts into *one* magnitude cut and a color cut.  E.g., in the north we have `21.0 > g < 23.7` and `r < 23.3`.  For many applications it's helpful to think about the sample as either being g- or r-band limited (in the FDR it was a g-band limit).  The results are of course the same but the added clarity is useful.

**Comment by sbailey** [comment]
Thanks @geordie666 for the updates and @moustakas thanks for the review.  @moustakas can you also confirm that this won't break select_mock_targets?  We have a historical fragility of changes to the "real data" cuts interfaces breaking mocks in ways that aren't caught by the simple unit tests.  Thanks.

**Comment by geordie666** [comment]
@moustakas: I'm done with this branch. If you get a chance, can you check that it doesn't break `select_mock_targets` and if it doesn't, merge it? 

Hopefully I won't have to ask that every time I update the "real data" cuts. My next effort is working on SV and secondary targets, so you should get a break from me pestering you for a while.

**Comment by moustakas** [comment]
Actually, it looks like #407 broke `select_mock_targets` in that the BGS selection now requires `FRACIN_[G,R,Z]`, which we'll need to add to the targets data model---
https://desidatamodel.readthedocs.io/en/latest/DESI_TARGET/targets.html

**Pull request merged**
