### PR TITLE
Scan through a directory.

### PR DESCRIPTION
**Pull request by rainwoodman**
```
targetselection.py src/ dest/
```

Add tsbits to all tractor files in src/ and save the result to dest/

### CODE REVIEW

**Comment by sbailey** [comment]
It looks like the iteration over tractor files will raise a ValueError if it encounters any non-tractor files in the directory tree.  It seems like it should just harmlessly step over them instead.

**Comment by rainwoodman** [comment]
Ha! Let me explain:

- parse_filename would raise a ValueError, but the iteration would catch it and pass though. 

- the function parse_filename is there to highlight that in other DRs the format of the filename may change.

**Comment by sbailey** [comment]
Gotcha.  I added comments to make that more obvious; removed a leftover (?) print statement, and make the regex more specific.  Will merge now.

**Comment by rainwoodman** [comment]
Thanks for the clean up!

**Pull request merged**
